export const FOO = "FOO";
export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const ISMOBILE = 'ISMOBILE'
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
